# footprint: [[0.0, 0.3], [-1.0, 0.3], [-1.0, -0.3], [0.0, -0.3]]
footprint: [[0.75, 0.3], [-0.05, 0.3], [-0.05, -0.3], [0.75, -0.3]]
footprint_padding: 0.2

# robot_base_frame: base_tip
robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: d435/depth/scan, inf_is_valid: true, observation_persistence: 7}
    footprint_clearing_enabled: false
    # laser: {data_type: LaserScan, clearing: true, marking: true, topic: d435/depth/scan, inf_is_valid: true, observation_persistence: 3}
    # laser: {data_type: LaserScan, clearing: true, marking: true, topic: d435/depth/scan, inf_is_valid: true}
    
inflation:
    inflation_radius: 0.5
